export const PROJECTS= [
    {
        title: "Todo List",
        description: "The Todo List application is a user-friendly task management tool that allows users to create, edit, delete, and mark tasks as completed. It features filters to hide completed tasks, a case-insensitive search for titles and descriptions, and a multi-select filter for task importance.",
        image: "./assets/Rectangle.png"
    }
]